INSERT INTO sbo_terms (id, name, comment, is_leaf) VALUES
('SBO:0000176', 'biochemical reaction', 'An event involving one or more chemical entities that modifies the electrochemical structure of at least one of the participants.', false),
('SBO:0000177', 'non-covalent binding', 'Synonym: association', true),
('SBO:0000179', 'degradation', 'Complete disappearance of a physical entity.', true),
('SBO:0000180', 'dissociation', 'Transformation of a non-covalent complex that results in the formation of several independent biochemical entities', true),
('SBO:0000181', 'conformational transition', 'Biochemical reaction that does not result in the modification of covalent bonds of reactants, but rather modifies the conformation of some reactants, that is the relative position of their atoms in space.', true),
('SBO:0000182', 'conversion', 'Biochemical reaction that results in the modification of some covalent bonds.', false),
('SBO:0000178', 'cleavage', 'Rupture of a covalent bond resulting in the conversion of one physical entity into several physical entities or into a physical entity of a different topological class.', false),
('SBO:0000376', 'hydrolysis', 'Decomposition of a compound by reaction with water, where the hydroxyl and H groups are incorporated into different products', true),
('SBO:0000210', 'addition of a chemical group', 'Covalent reaction that results in the addition of a chemical group on a molecule.', false),
('SBO:0000212', 'protonation', 'Addition of a proton (H+) to a chemical entity.', true),
('SBO:0000214', 'methylation', 'Addition of a methyl group (-CH3) to a chemical entity.', true),
('SBO:0000215', 'acetylation', 'Addition of an acetyl group (-COCH3) to a chemical entity.', true),
('SBO:0000216', 'phosphorylation', 'Addition of a phosphate group (-H2PO4) to a chemical entity.', true),
('SBO:0000217', 'glycosylation', 'Addition of a saccharide group to a chemical entity.', true),
('SBO:0000218', 'palmitoylation', 'Addition of a palmitoyl group (CH3-[CH2]14-CO-) to a chemical entity.', true),
('SBO:0000219', 'myristoylation', 'Addition of a myristoyl (CH3-[CH2]12-CO-) to a chemical entity.', true),
('SBO:0000220', 'sulfation', 'Synonym: sulphation', true),
('SBO:0000221', 'prenylation', 'Synonym: isoprenylation', false),
('SBO:0000222', 'farnesylation', 'Addition of a farnesyl group (CH2-CH=C(CH3)-CH2-CH2-CH=C(CH3)-CH2-CH2-CH=C(CH3)2) to a chemical entity.', true),
('SBO:0000223', 'geranylgeranylation', 'Addition of a geranylgeranyl group (CH2-CH=C(CH3)-CH2-CH2-CH=C(CH3)-CH2-CH2-CH=C(CH3)-CH2-CH2-CH=C(CH3)2) to a chemical entity.', true),
('SBO:0000224', 'ubiquitination', 'Covalent linkage to the protein ubiquitin.', true),
('SBO:0000233', 'hydroxylation', 'Addition of an hydroxyl group (-OH) to a chemical entity.', true),
('SBO:0000211', 'removal of a chemical group', 'Covalent reaction that results in the removal of a chemical group from a molecule.', false),
('SBO:0000213', 'deprotonation', 'Removal of a proton (hydrogen ion H+) from a chemical entity.', true),
('SBO:0000330', 'dephosphorylation', 'Removal of a phosphate group (-H2PO4) from a chemical entity.', true),
('SBO:0000399', 'decarboxylation', 'A process in which a carboxyl group (COOH) is removed from a molecule as carbon dioxide.', true),
('SBO:0000400', 'decarbonylation', 'Removal of a carbonyl group (-C-O-) from a molecule, usually as carbon monoxide', true),
('SBO:0000401', 'deamination', 'Removal of an amine group from a molecule, often under the addition of water', true),
('SBO:0000402', 'transfer of a chemical group', 'Covalent reaction that results in the transfer of a chemical group from one molecule to another.', false),
('SBO:0000403', 'transamination', 'The transfer of an amino group between two molecules. Commonly in biology this is restricted to reactions between an amino acid and an alpha-keto carbonic acid, whereby the reacting amino acid is converted into an alpha-keto acid, and the alpha-keto acid reactant into an amino acid.', true),
('SBO:0000652', 'polymerization', 'A chemical reaction in which one or more monomer molecules combine to form a larger polymer molecule with repeated structural units.', true),
('SBO:0000653', 'depolymerization', 'A chemical reaction in which a large polymer breaks into its constituent monomers (or mixture of monomers).', true),
('SBO:0000656', 'activation', 'A conformational change in a protein resulting in its activation.', true),
('SBO:0000665', 'inactivation', 'a conformation changes to a protein leading to its inactivation', true),
('SBO:0000695', 'ligation', 'Formation of a covalent bond resulting in the creation of a link between the ends of one or more linear polymer molecules.', true),
('SBO:0000200', 'redox reaction', 'Chemical process in which atoms have their oxidation number (oxidation state) changed.', false),
('SBO:0000201', 'oxidation', 'Chemical process during which a molecular entity loses electrons.', true),
('SBO:0000202', 'reduction', 'Chemical process in which a molecular entity gain electrons.', true),
('SBO:0000208', 'acid-base reaction', 'Chemical reaction where a proton is given by a compound, the acid, to another one, the base (Brønsted-Lowry definition). An alternative, more general, definition is a reaction where a compound, the base, gives a pair of electrons to another, the acid (Lewis definition).', false),
('SBO:0000209', 'ionisation', 'Ionization is the physical process of converting an atom or molecule into an ion by changing the difference between the number of protons and electrons.', true),
('SBO:0000377', 'isomerisation', 'A reaction in which the principal reactant and principal product are isomers of each other', true),
('SBO:0000672', 'spontaneous reaction', 'Reaction with no catalyst (no enzyme in particular) is needed to proceed.', true);