import unittest
import tempfile
import os
from unittest.mock import Mock
import sys

# Add the project root to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from src.ols_fetch_from_github.obo_parser import OBOFileParser
from src.ols_fetch_from_github.config import Config


class TestOBOFileParser(unittest.TestCase):
    """Test cases for OBOFileParser class"""
    
    def setUp(self):
        """Set up test fixtures"""
        self.mock_config = Mock(spec=Config)
        self.parser = OBOFileParser(self.mock_config)
        
        # Sample OBO content for testing
        self.sample_obo_content = """format-version: 1.2
remark: Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)
ontology: http://biomodels.net/SBO/
property_value: owl:versionInfo "28:08:2021 03:13" xsd:string
name: Generated: 03:11:2021 07:00

[Term]
id: SBO:0000001
name: rate law
comment: mathematical description that relates quantities of reactants to the reaction velocity.
is_a: SBO:0000064 ! mathematical expression

[Term]
id: SBO:0000002
name: quantitative systems description parameter
comment: A numerical value that defines certain characteristics of systems or system functions.
is_a: SBO:0000545 ! systems description parameter

[Typedef]
id: part:of
name: part of
is_transitive: true
"""
    
    def test_parse_obo_file_complete(self):
        """Test parsing a complete OBO file"""
        # Create temporary file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.obo', delete=False) as f:
            f.write(self.sample_obo_content)
            temp_file = f.name
        
        try:
            result = self.parser.parse_obo_file(temp_file)
            
            # Verify header
            self.assertIn('header', result)
            header = result['header']
            self.assertEqual(header['format-version'], '1.2')
            self.assertEqual(header['remark'], 'Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)')
            self.assertEqual(header['ontology'], 'http://biomodels.net/SBO/')
            self.assertEqual(header['property_value'], 'owl:versionInfo "28:08:2021 03:13" xsd:string')
            self.assertEqual(header['name'], 'Generated: 03:11:2021 07:00')
            
            # Verify terms
            self.assertIn('terms', result)
            terms = result['terms']
            self.assertEqual(len(terms), 2)
            
            # Check first term
            term1 = terms[0]
            self.assertEqual(term1['id'], 'SBO:0000001')
            self.assertEqual(term1['name'], 'rate law')
            self.assertEqual(term1['comment'], 'mathematical description that relates quantities of reactants to the reaction velocity.')
            
            # Check is_a relationship
            self.assertIn('is_a', term1)
            is_a = term1['is_a'][0]
            self.assertEqual(is_a['id'], 'SBO:0000064')
            self.assertEqual(is_a['name'], 'mathematical expression')
            
            # Check second term
            term2 = terms[1]
            self.assertEqual(term2['id'], 'SBO:0000002')
            self.assertEqual(term2['name'], 'quantitative systems description parameter')
            self.assertEqual(term2['comment'], 'A numerical value that defines certain characteristics of systems or system functions.')
            
            # Check second term's is_a relationship
            self.assertIn('is_a', term2)
            is_a2 = term2['is_a'][0]
            self.assertEqual(is_a2['id'], 'SBO:0000545')
            self.assertEqual(is_a2['name'], 'systems description parameter')
            
            # Verify typedefs
            self.assertIn('typedefs', result)
            typedefs = result['typedefs']
            self.assertEqual(len(typedefs), 1)
            
            typedef1 = typedefs[0]
            self.assertEqual(typedef1['id'], 'part:of')
            self.assertEqual(typedef1['name'], 'part of')
            self.assertEqual(typedef1['is_transitive'], 'true')
            
        finally:
            os.unlink(temp_file)
    
    def test_parse_header_only(self):
        """Test parsing file with header only"""
        header_only_content = """format-version: 1.2
remark: Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)
ontology: http://biomodels.net/SBO/

"""
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.obo', delete=False) as f:
            f.write(header_only_content)
            temp_file = f.name
        
        try:
            result = self.parser.parse_obo_file(temp_file)
            
            self.assertIn('header', result)
            self.assertEqual(len(result['header']), 3)
            self.assertEqual(result['header']['format-version'], '1.2')
            self.assertEqual(result['header']['remark'], 'Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)')
            self.assertEqual(result['header']['ontology'], 'http://biomodels.net/SBO/')
            self.assertIn('terms', result)
            self.assertEqual(len(result['terms']), 0)
            self.assertNotIn('typedefs', result)
            
        finally:
            os.unlink(temp_file)
    
    def test_parse_header(self):
        """Test header parsing"""
        header_content = """format-version: 1.2
remark: Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)
ontology: http://biomodels.net/SBO/
property_value: owl:versionInfo "28:08:2021 03:13" xsd:string
name: Generated: 03:11:2021 07:00
"""
        
        result = self.parser._parse_header(header_content)
        
        self.assertEqual(len(result), 5)
        self.assertEqual(result['format-version'], '1.2')
        self.assertEqual(result['remark'], 'Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)')
        self.assertEqual(result['ontology'], 'http://biomodels.net/SBO/')
        self.assertEqual(result['property_value'], 'owl:versionInfo "28:08:2021 03:13" xsd:string')
        self.assertEqual(result['name'], 'Generated: 03:11:2021 07:00')
    
    def test_parse_section_term(self):
        """Test parsing a term section"""
        term_content = """id: SBO:0000001
name: rate law
comment: mathematical description that relates quantities of reactants to the reaction velocity.
is_a: SBO:0000064 ! mathematical expression
is_a: SBO:0000065 ! another parent
"""
        
        result = self.parser._parse_section(term_content)
        
        self.assertEqual(result['id'], 'SBO:0000001')
        self.assertEqual(result['name'], 'rate law')
        self.assertEqual(result['comment'], 'mathematical description that relates quantities of reactants to the reaction velocity.')
        
        # Check is_a list
        self.assertIsInstance(result['is_a'], list)
        self.assertEqual(len(result['is_a']), 2)
        self.assertEqual(result['is_a'][0]['id'], 'SBO:0000064')
        self.assertEqual(result['is_a'][0]['name'], 'mathematical expression')
        self.assertEqual(result['is_a'][1]['id'], 'SBO:0000065')
        self.assertEqual(result['is_a'][1]['name'], 'another parent')
    
    def test_handle_is_a_field_with_comment(self):
        """Test handling is_a field with comment"""
        parsed_section = {}
        
        self.parser._handle_is_a_field(parsed_section, 'is_a', 'SBO:0000064 ! mathematical expression')
        
        self.assertIn('is_a', parsed_section)
        self.assertEqual(len(parsed_section['is_a']), 1)
        self.assertEqual(parsed_section['is_a'][0]['id'], 'SBO:0000064')
        self.assertEqual(parsed_section['is_a'][0]['name'], 'mathematical expression')
    
    def test_handle_is_a_field_without_comment(self):
        """Test handling is_a field without comment"""
        parsed_section = {}
        
        self.parser._handle_is_a_field(parsed_section, 'is_a', 'SBO:0000064')
        
        self.assertIn('is_a', parsed_section)
        self.assertEqual(len(parsed_section['is_a']), 1)
        self.assertEqual(parsed_section['is_a'][0], 'SBO:0000064')
    
    def test_handle_regular_field_single_value(self):
        """Test handling regular field with single value"""
        parsed_section = {}
        
        self.parser._handle_regular_field(parsed_section, 'name', 'rate law')
        
        self.assertEqual(parsed_section['name'], 'rate law')
    
    def test_handle_regular_field_multiple_values(self):
        """Test handling regular field with multiple is_a values (fallback case)"""
        parsed_section = {}
        
        # Test with a hypothetical field that could have multiple values
        self.parser._handle_regular_field(parsed_section, 'comment', 'first comment')
        self.parser._handle_regular_field(parsed_section, 'comment', 'second comment')
        
        # Since comment would normally be single value, this tests the multiple value handling
        self.assertIsInstance(parsed_section['comment'], list)
        self.assertEqual(len(parsed_section['comment']), 2)
        self.assertEqual(parsed_section['comment'][0], 'first comment')
        self.assertEqual(parsed_section['comment'][1], 'second comment')
    
    def test_parse_empty_file(self):
        """Test parsing empty file"""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.obo', delete=False) as f:
            f.write("")
            temp_file = f.name
        
        try:
            result = self.parser.parse_obo_file(temp_file)
            
            self.assertIn('header', result)
            self.assertEqual(len(result['header']), 0)
            self.assertIn('terms', result)
            self.assertEqual(len(result['terms']), 0)
            
        finally:
            os.unlink(temp_file)
    
    def test_parse_malformed_line(self):
        """Test parsing file with malformed lines"""
        malformed_content = """format-version: 1.2
this line has no colon
ontology: http://biomodels.net/SBO/

[Term]
id: SBO:0000001
malformed line without colon
name: rate law
"""
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.obo', delete=False) as f:
            f.write(malformed_content)
            temp_file = f.name
        
        try:
            result = self.parser.parse_obo_file(temp_file)
            
            # Should parse successfully, ignoring malformed lines
            self.assertIn('header', result)
            self.assertEqual(result['header']['format-version'], '1.2')
            self.assertEqual(result['header']['ontology'], 'http://biomodels.net/SBO/')
            
            self.assertIn('terms', result)
            self.assertEqual(len(result['terms']), 1)
            self.assertEqual(result['terms'][0]['id'], 'SBO:0000001')
            self.assertEqual(result['terms'][0]['name'], 'rate law')
            
        finally:
            os.unlink(temp_file)


if __name__ == '__main__':
    unittest.main()