import unittest
import tempfile
import os
import json
import shutil
import glob
from unittest.mock import Mock, patch, MagicMock
from datetime import datetime
import sys

# Add the project root to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from src.ols_fetch_from_github.github_file_updater import GitHubFileUpdater


class TestGitHubFileUpdater(unittest.TestCase):
    """Test cases for GitHubFileUpdater class"""
    
    def setUp(self):
        """Set up test fixtures"""
        self.test_dir = tempfile.mkdtemp()
        self.original_cwd = os.getcwd()
        
        # Create test directory structure
        self.localfiles_dir = os.path.join(self.test_dir, 'localfiles')
        os.makedirs(self.localfiles_dir)
        
        # Mock configuration
        self.mock_config = Mock()
        self.mock_config.github_url = 'https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OBO.obo'
        self.mock_config.github_repo_owner = 'EBI-BioModels'
        self.mock_config.github_repo_name = 'SBO'
        self.mock_config.github_file_path = 'SBO_OBO.obo'
        self.mock_config.timestamp_format = '%Y%m%d_%H%M%S'
        
        # Mock directory manager
        self.mock_directory_manager = Mock()
        self.mock_directory_manager.get_localfiles_dir.return_value = self.localfiles_dir
        self.mock_directory_manager.ensure_all_directories.return_value = None
        
        # Mock components
        self.mock_downloader = Mock()
        self.mock_parser = Mock()
        self.mock_converter = Mock()
        self.mock_validator = Mock()
        self.mock_comparator = Mock()
        
        # Sample data based on actual SBO structure
        self.sample_remote_info = {
            'sha': 'abc123',
            'last_modified': '2023-05-15T10:30:45Z',
            'size': 1024,
            'download_url': 'https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OBO.obo'
        }
        
        self.sample_local_info = {
            'sha': 'def456',
            'last_modified': '2023-05-01T10:30:45Z',
            'size': 1000,
            'local_update_time': '2023-05-01T10:30:45'
        }
        
        self.sample_json_data = {
            'header': {
                'format-version': '1.2',
                'remark': 'Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)',
                'ontology': 'http://biomodels.net/SBO/',
                'property_value': 'owl:versionInfo "28:08:2021 03:13" xsd:string',
                'name': 'Generated: 03:11:2021 07:00'
            },
            'terms': [
                {
                    'id': 'SBO:0000001',
                    'name': 'rate law',
                    'comment': 'mathematical description that relates quantities of reactants to the reaction velocity.',
                    'is_a': [{'id': 'SBO:0000064', 'name': 'mathematical expression'}]
                }
            ],
            'typedefs': [
                {
                    'id': 'part:of',
                    'name': 'part of',
                    'is_transitive': 'true'
                }
            ]
        }
        
        self.sample_changes = {
            'has_changes': True,
            'stats': {
                'terms_added': 1,
                'terms_deleted': 0,
                'terms_updated': 1,
                'typedefs_added': 0,
                'typedefs_deleted': 0,
                'typedefs_updated': 0,
                'header_updated': True
            },
            'term_changes': {
                'added': [
                    {
                        'id': 'SBO:0000001',
                        'name': 'rate law',
                        'comment': 'mathematical description that relates quantities of reactants to the reaction velocity.',
                        'is_a': [{'id': 'SBO:0000064', 'name': 'mathematical expression'}]
                    }
                ],
                'deleted': [],
                'updated': []
            },
            'typedef_changes': {
                'added': [],
                'deleted': [],
                'updated': []
            }
        }
        
        self.no_changes = {
            'has_changes': False,
            'stats': {
                'terms_added': 0,
                'terms_deleted': 0,
                'terms_updated': 0,
                'typedefs_added': 0,
                'typedefs_deleted': 0,
                'typedefs_updated': 0,
                'header_updated': False
            }
        }
    
    def tearDown(self):
        """Clean up test fixtures"""
        os.chdir(self.original_cwd)
        shutil.rmtree(self.test_dir, ignore_errors=True)
        
        # Clean up any stray files in tests directory
        test_files_pattern = [
            'SBO_OBO_*.obo',
            'SBO_OBO_*.json', 
            'SBO_OBO_*.obo.update_info'
        ]
        
        tests_dir = os.path.dirname(__file__)
        for pattern in test_files_pattern:
            for file_path in glob.glob(os.path.join(tests_dir, pattern)):
                try:
                    os.remove(file_path)
                except OSError:
                    pass  # Ignore errors if file doesn't exist
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_init_with_config(self, mock_comparator_class, mock_validator_class, 
                              mock_converter_class, mock_parser_class, 
                              mock_downloader_class, mock_directory_manager_class):
        """Test initialization with config"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        updater = GitHubFileUpdater(config=self.mock_config)
        
        self.assertEqual(updater.config, self.mock_config)
        self.assertEqual(updater.base_filename, 'SBO_OBO.obo')
        
        # Check directory manager setup
        mock_directory_manager_class.assert_called_once_with(self.mock_config)
        self.mock_directory_manager.ensure_all_directories.assert_called_once()
        
        # Check component initialization
        mock_downloader_class.assert_called_once_with(self.mock_config)
        mock_parser_class.assert_called_once_with(self.mock_config)
        mock_converter_class.assert_called_once_with(self.mock_config)
        mock_validator_class.assert_called_once()
        mock_comparator_class.assert_called_once()
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    @patch('src.ols_fetch_from_github.github_file_updater.Config')
    def test_init_default_config(self, mock_config_class, mock_comparator_class, 
                                 mock_validator_class, mock_converter_class, 
                                 mock_parser_class, mock_downloader_class, 
                                 mock_directory_manager_class):
        """Test initialization with default config"""
        mock_config_class.return_value = self.mock_config
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        updater = GitHubFileUpdater()
        
        mock_config_class.assert_called_once()
        self.assertEqual(updater.config, self.mock_config)
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_get_update_status_needs_update(self, mock_comparator_class, mock_validator_class, 
                                           mock_converter_class, mock_parser_class, 
                                           mock_downloader_class, mock_directory_manager_class):
        """Test get_update_status when update is needed"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        # Mock return values
        self.mock_downloader.get_remote_file_info.return_value = self.sample_remote_info
        
        # Create local info file
        local_info_file = os.path.join(self.localfiles_dir, 'SBO_OBO.obo.update_info')
        with open(local_info_file, 'w') as f:
            json.dump(self.sample_local_info, f)
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            updater.info_file = local_info_file
            
            status = updater.get_update_status()
        
        self.assertFalse(status['local_file_exists'])
        self.assertTrue(status['has_local_info'])
        self.assertTrue(status['remote_info_available'])
        self.assertTrue(status['needs_update'])
        self.assertEqual(status['local_sha'], self.sample_local_info['sha'])
        self.assertEqual(status['remote_sha'], self.sample_remote_info['sha'])
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_get_update_status_no_update_needed(self, mock_comparator_class, mock_validator_class, 
                                               mock_converter_class, mock_parser_class, 
                                               mock_downloader_class, mock_directory_manager_class):
        """Test get_update_status when no update is needed"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        # Same SHA means no update needed
        same_sha_remote = self.sample_remote_info.copy()
        same_sha_remote['sha'] = self.sample_local_info['sha']
        
        self.mock_downloader.get_remote_file_info.return_value = same_sha_remote
        
        local_info_file = os.path.join(self.localfiles_dir, 'SBO_OBO.obo.update_info')
        with open(local_info_file, 'w') as f:
            json.dump(self.sample_local_info, f)
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            updater.info_file = local_info_file
            
            status = updater.get_update_status()
        
        self.assertFalse(status['needs_update'])
        self.assertEqual(status['local_sha'], status['remote_sha'])
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_auto_download_update_success(self, mock_comparator_class, mock_validator_class, 
                                         mock_converter_class, mock_parser_class, 
                                         mock_downloader_class, mock_directory_manager_class):
        """Test successful auto download update"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        # Mock return values
        temp_obo_file = os.path.join(self.test_dir, 'temp_file.obo')
        temp_json_file = os.path.join(self.test_dir, 'temp_file.json')
        
        self.mock_downloader.get_remote_file_info.return_value = self.sample_remote_info
        self.mock_downloader.download_to_temp.return_value = temp_obo_file
        self.mock_parser.parse_obo_file.return_value = self.sample_json_data
        self.mock_validator.validate_roundtrip_conversion.return_value = True
        
        # Create temp files
        with open(temp_obo_file, 'w') as f:
            f.write('test obo content')
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            
            with patch('builtins.open', side_effect=open):
                result = updater.auto_download_update()
        
        self.assertIsNotNone(result)
        self.assertEqual(result['temp_obo_file'], temp_obo_file)
        self.assertTrue(result['temp_json_file'].endswith('.json'))
        self.assertEqual(result['remote_info'], self.sample_remote_info)
        self.assertFalse(result['has_changes'])  # No local file to compare
        
        # Verify component calls
        self.mock_downloader.get_remote_file_info.assert_called_once()
        self.mock_downloader.download_to_temp.assert_called_once_with(self.sample_remote_info)
        self.mock_parser.parse_obo_file.assert_called_once_with(temp_obo_file)
        self.mock_validator.validate_roundtrip_conversion.assert_called_once()
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_auto_download_update_no_remote_info(self, mock_comparator_class, mock_validator_class, 
                                                 mock_converter_class, mock_parser_class, 
                                                 mock_downloader_class, mock_directory_manager_class):
        """Test auto download update when remote info is not available"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        self.mock_downloader.get_remote_file_info.return_value = None
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            result = updater.auto_download_update()
        
        self.assertIsNone(result)
        self.mock_downloader.get_remote_file_info.assert_called_once()
        self.mock_downloader.download_to_temp.assert_not_called()
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_auto_download_update_download_failure(self, mock_comparator_class, mock_validator_class, 
                                                   mock_converter_class, mock_parser_class, 
                                                   mock_downloader_class, mock_directory_manager_class):
        """Test auto download update when download fails"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        self.mock_downloader.get_remote_file_info.return_value = self.sample_remote_info
        self.mock_downloader.download_to_temp.return_value = None
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            result = updater.auto_download_update()
        
        self.assertIsNone(result)
        self.mock_downloader.download_to_temp.assert_called_once()
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_auto_download_update_validation_failure(self, mock_comparator_class, mock_validator_class, 
                                                     mock_converter_class, mock_parser_class, 
                                                     mock_downloader_class, mock_directory_manager_class):
        """Test auto download update when validation fails"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        temp_obo_file = os.path.join(self.test_dir, 'temp_file.obo')
        
        self.mock_downloader.get_remote_file_info.return_value = self.sample_remote_info
        self.mock_downloader.download_to_temp.return_value = temp_obo_file
        self.mock_parser.parse_obo_file.return_value = self.sample_json_data
        self.mock_validator.validate_roundtrip_conversion.return_value = False
        
        # Create temp file
        with open(temp_obo_file, 'w') as f:
            f.write('test obo content')
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            
            with patch('builtins.open', side_effect=open):
                result = updater.auto_download_update()
        
        self.assertIsNone(result)
        self.mock_validator.validate_roundtrip_conversion.assert_called_once()
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_apply_downloaded_update_success(self, mock_comparator_class, mock_validator_class, 
                                            mock_converter_class, mock_parser_class, 
                                            mock_downloader_class, mock_directory_manager_class):
        """Test successful apply downloaded update"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        # Create temp files
        temp_obo_file = os.path.join(self.test_dir, 'temp_file.obo')
        temp_json_file = os.path.join(self.test_dir, 'temp_file.json')
        
        with open(temp_obo_file, 'w') as f:
            f.write('test obo content')
        with open(temp_json_file, 'w') as f:
            json.dump(self.sample_json_data, f)
        
        update_info = {
            'temp_obo_file': temp_obo_file,
            'temp_json_file': temp_json_file,
            'remote_info': self.sample_remote_info,
            'changes': self.sample_changes,
            'has_changes': True
        }
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            
            with patch('src.ols_fetch_from_github.github_file_updater.shutil.move') as mock_move:
                with patch('src.ols_fetch_from_github.change_logger.ChangeLogger') as mock_logger_class:
                    mock_logger = Mock()
                    mock_logger_class.return_value = mock_logger
                    
                    result = updater.apply_downloaded_update(update_info)
        
        self.assertTrue(result)
        self.assertEqual(mock_move.call_count, 2)  # Move both temp files
        mock_logger.log_changes.assert_called_once()
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_apply_downloaded_update_no_info(self, mock_comparator_class, mock_validator_class, 
                                            mock_converter_class, mock_parser_class, 
                                            mock_downloader_class, mock_directory_manager_class):
        """Test apply downloaded update with no update info"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            result = updater.apply_downloaded_update(None)
        
        self.assertFalse(result)
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_cleanup_temp_update(self, mock_comparator_class, mock_validator_class, 
                                 mock_converter_class, mock_parser_class, 
                                 mock_downloader_class, mock_directory_manager_class):
        """Test cleanup of temporary update files"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        # Create temp files
        temp_obo_file = os.path.join(self.test_dir, 'temp_file.obo')
        temp_json_file = os.path.join(self.test_dir, 'temp_file.json')
        
        with open(temp_obo_file, 'w') as f:
            f.write('test obo content')
        with open(temp_json_file, 'w') as f:
            json.dump(self.sample_json_data, f)
        
        update_info = {
            'temp_obo_file': temp_obo_file,
            'temp_json_file': temp_json_file
        }
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            
            with patch('src.ols_fetch_from_github.github_file_updater.FileUtils.cleanup_files') as mock_cleanup:
                updater.cleanup_temp_update(update_info)
        
        mock_cleanup.assert_called_once_with([temp_obo_file, temp_json_file])
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_cleanup_temp_update_no_info(self, mock_comparator_class, mock_validator_class, 
                                         mock_converter_class, mock_parser_class, 
                                         mock_downloader_class, mock_directory_manager_class):
        """Test cleanup with no update info"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            
            with patch('src.ols_fetch_from_github.github_file_updater.FileUtils.cleanup_files') as mock_cleanup:
                updater.cleanup_temp_update(None)
        
        mock_cleanup.assert_not_called()
    
    
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_load_local_info_success(self, mock_comparator_class, mock_validator_class, 
                                     mock_converter_class, mock_parser_class, 
                                     mock_downloader_class, mock_directory_manager_class):
        """Test successful loading of local info"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        # Create info file
        info_file = os.path.join(self.localfiles_dir, 'test_info.json')
        with open(info_file, 'w') as f:
            json.dump(self.sample_local_info, f)
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            updater.info_file = info_file
            
            result = updater.load_local_info()
        
        self.assertEqual(result, self.sample_local_info)
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_load_local_info_nonexistent(self, mock_comparator_class, mock_validator_class, 
                                         mock_converter_class, mock_parser_class, 
                                         mock_downloader_class, mock_directory_manager_class):
        """Test loading local info when file doesn't exist"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            updater.info_file = os.path.join(self.localfiles_dir, 'nonexistent.json')
            
            result = updater.load_local_info()
        
        self.assertIsNone(result)
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_load_local_info_invalid_json(self, mock_comparator_class, mock_validator_class, 
                                          mock_converter_class, mock_parser_class, 
                                          mock_downloader_class, mock_directory_manager_class):
        """Test loading local info with invalid JSON"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        # Create invalid JSON file
        info_file = os.path.join(self.localfiles_dir, 'invalid.json')
        with open(info_file, 'w') as f:
            f.write('invalid json {')
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            updater.info_file = info_file
            
            result = updater.load_local_info()
        
        self.assertIsNone(result)
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_save_local_info_success(self, mock_comparator_class, mock_validator_class, 
                                     mock_converter_class, mock_parser_class, 
                                     mock_downloader_class, mock_directory_manager_class):
        """Test successful saving of local info"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        info_file = os.path.join(self.localfiles_dir, 'test_info.json')
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            updater.info_file = info_file
            
            with patch('src.ols_fetch_from_github.github_file_updater.datetime') as mock_datetime:
                mock_datetime.now.return_value.isoformat.return_value = '2023-05-15T10:30:45'
                
                updater.save_local_info(self.sample_remote_info)
        
        self.assertTrue(os.path.exists(info_file))
        with open(info_file, 'r') as f:
            saved_info = json.load(f)
        
        self.assertEqual(saved_info['sha'], self.sample_remote_info['sha'])
        self.assertEqual(saved_info['local_update_time'], '2023-05-15T10:30:45')
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_cleanup_working_directory(self, mock_comparator_class, mock_validator_class, 
                                       mock_converter_class, mock_parser_class, 
                                       mock_downloader_class, mock_directory_manager_class):
        """Test cleanup restores working directory"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        original_cwd = os.getcwd()
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir') as mock_chdir:
            updater = GitHubFileUpdater(config=self.mock_config)
            updater.original_cwd = original_cwd
            
            updater.cleanup()
        
        mock_chdir.assert_called_with(original_cwd)
    
    @patch('src.ols_fetch_from_github.github_file_updater.DirectoryManager')
    @patch('src.ols_fetch_from_github.github_file_updater.GitHubFileDownloader')
    @patch('src.ols_fetch_from_github.github_file_updater.OBOFileParser')
    @patch('src.ols_fetch_from_github.github_file_updater.FileConverter')
    @patch('src.ols_fetch_from_github.github_file_updater.FileValidator')
    @patch('src.ols_fetch_from_github.github_file_updater.FileComparator')
    def test_find_latest_local_file(self, mock_comparator_class, mock_validator_class, 
                                    mock_converter_class, mock_parser_class, 
                                    mock_downloader_class, mock_directory_manager_class):
        """Test finding latest local file"""
        mock_directory_manager_class.return_value = self.mock_directory_manager
        mock_downloader_class.return_value = self.mock_downloader
        mock_parser_class.return_value = self.mock_parser
        mock_converter_class.return_value = self.mock_converter
        mock_validator_class.return_value = self.mock_validator
        mock_comparator_class.return_value = self.mock_comparator
        
        with patch('src.ols_fetch_from_github.github_file_updater.os.chdir'):
            updater = GitHubFileUpdater(config=self.mock_config)
            
            with patch('src.ols_fetch_from_github.github_file_updater.FileUtils.find_latest_timestamped_file') as mock_find:
                mock_find.return_value = 'SBO_OBO_20230515_103045.obo'
                
                result = updater._find_latest_local_file()
        
        self.assertEqual(result, 'SBO_OBO_20230515_103045.obo')
        mock_find.assert_called_once_with('SBO_OBO_*.obo', self.localfiles_dir)


if __name__ == '__main__':
    unittest.main()