import unittest
import tempfile
import os
import json
from unittest.mock import Mock
import sys

# Add the project root to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from src.ols_fetch_from_github.file_converter import FileConverter
from src.ols_fetch_from_github.config import Config


class TestFileConverter(unittest.TestCase):
    """Test cases for FileConverter class"""
    
    def setUp(self):
        """Set up test fixtures"""
        self.mock_config = Mock(spec=Config)
        self.mock_config.obo_field_order = ['id', 'name', 'comment', 'is_a']
        self.mock_config.typedef_field_order = ['id', 'name', 'is_transitive']
        
        self.converter = FileConverter(self.mock_config)
        
        # Sample JSON data for testing
        self.sample_json_data = {
            "header": {
                "format-version": "1.2",
                "remark": "Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)",
                "ontology": "http://biomodels.net/SBO/",
                "property_value": "owl:versionInfo \"28:08:2021 03:13\" xsd:string",
                "name": "Generated: 03:11:2021 07:00"
            },
            "terms": [
                {
                    "id": "SBO:0000001",
                    "name": "rate law",
                    "comment": "mathematical description that relates quantities of reactants to the reaction velocity.",
                    "is_a": [
                        {
                            "id": "SBO:0000064",
                            "name": "mathematical expression"
                        }
                    ]
                },
                {
                    "id": "SBO:0000002",
                    "name": "quantitative systems description parameter",
                    "comment": "A numerical value that defines certain characteristics of systems or system functions.",
                    "is_a": [
                        {
                            "id": "SBO:0000545",
                            "name": "systems description parameter"
                        }
                    ]
                }
            ],
            "typedefs": [
                {
                    "id": "part:of",
                    "name": "part of",
                    "is_transitive": "true"
                }
            ]
        }
    
    def test_convert_json_to_obo_complete(self):
        """Test complete JSON to OBO conversion"""
        # Create temporary JSON file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as json_file:
            json.dump(self.sample_json_data, json_file)
            json_file_path = json_file.name
        
        # Create temporary OBO file path
        with tempfile.NamedTemporaryFile(mode='w', suffix='.obo', delete=False) as obo_file:
            obo_file_path = obo_file.name
        
        try:
            # Convert JSON to OBO
            self.converter.convert_json_to_obo(json_file_path, obo_file_path)
            
            # Read and verify the OBO file
            with open(obo_file_path, 'r', encoding='utf-8') as f:
                obo_content = f.read()
            
            # Verify header section
            self.assertIn('format-version: 1.2', obo_content)
            self.assertIn('remark: Systems Biology Ontology', obo_content)
            self.assertIn('ontology: http://biomodels.net/SBO/', obo_content)
            
            # Verify term sections
            self.assertIn('[Term]', obo_content)
            self.assertIn('id: SBO:0000001', obo_content)
            self.assertIn('name: rate law', obo_content)
            self.assertIn('comment: mathematical description that relates quantities of reactants to the reaction velocity.', obo_content)
            self.assertIn('is_a: SBO:0000064 ! mathematical expression', obo_content)
            
            # Verify second term
            self.assertIn('id: SBO:0000002', obo_content)
            self.assertIn('name: quantitative systems description parameter', obo_content)
            
            # Verify typedef section
            self.assertIn('[Typedef]', obo_content)
            self.assertIn('id: part:of', obo_content)
            self.assertIn('name: part of', obo_content)
            self.assertIn('is_transitive: true', obo_content)
            
        finally:
            os.unlink(json_file_path)
            os.unlink(obo_file_path)
    
    def test_write_header(self):
        """Test header writing"""
        header = {
            "format-version": "1.2",
            "ontology": "test",
            "data-version": "2023-01-01"
        }
        
        obo_lines = []
        self.converter._write_header(header, obo_lines)
        
        self.assertEqual(len(obo_lines), 4)  # 3 header lines + 1 empty line
        self.assertIn('format-version: 1.2', obo_lines)
        self.assertIn('ontology: test', obo_lines)
        self.assertIn('data-version: 2023-01-01', obo_lines)
        self.assertEqual(obo_lines[-1], '')  # Empty line after header
    
    def test_write_terms(self):
        """Test terms writing"""
        terms = [
            {
                "id": "SBO:0000001",
                "name": "test term",
                "comment": "Test definition"
            }
        ]
        
        obo_lines = []
        self.converter._write_terms(terms, obo_lines)
        
        self.assertIn('[Term]', obo_lines)
        self.assertIn('id: SBO:0000001', obo_lines)
        self.assertIn('name: test term', obo_lines)
        self.assertIn('comment: Test definition', obo_lines)
        self.assertEqual(obo_lines[-1], '')  # Empty line after term
    
    def test_write_typedefs(self):
        """Test typedefs writing"""
        typedefs = [
            {
                "id": "part:of",
                "name": "part of",
                "is_transitive": "true"
            }
        ]
        
        obo_lines = []
        self.converter._write_typedefs(typedefs, obo_lines)
        
        self.assertIn('[Typedef]', obo_lines)
        self.assertIn('id: part:of', obo_lines)
        self.assertIn('name: part of', obo_lines)
        self.assertIn('is_transitive: true', obo_lines)
        self.assertEqual(obo_lines[-1], '')  # Empty line after typedef
    
    def test_write_fields_in_order(self):
        """Test writing fields in specified order"""
        data = {
            "id": "SBO:0000001",
            "name": "rate law",
            "comment": "mathematical description that relates quantities of reactants to the reaction velocity.",
            "is_a": [{"id": "SBO:0000064", "name": "mathematical expression"}]
        }
        
        field_order = ['id', 'name', 'comment', 'is_a']
        obo_lines = []
        
        self.converter._write_fields_in_order(data, field_order, obo_lines)
        
        # Check that ordered fields come first
        id_index = obo_lines.index('id: SBO:0000001')
        name_index = obo_lines.index('name: rate law')
        comment_index = obo_lines.index('comment: mathematical description that relates quantities of reactants to the reaction velocity.')
        
        self.assertLess(id_index, name_index)
        self.assertLess(name_index, comment_index)
        
        # Check that is_a field is present in correct format
        self.assertIn('is_a: SBO:0000064 ! mathematical expression', obo_lines)
    
    def test_write_field_simple_value(self):
        """Test writing field with simple value"""
        obo_lines = []
        
        self.converter._write_field('name', 'test term', obo_lines)
        
        self.assertEqual(len(obo_lines), 1)
        self.assertEqual(obo_lines[0], 'name: test term')
    
    def test_write_field_list_value(self):
        """Test writing field with list value"""
        obo_lines = []
        
        self.converter._write_field('comment', ['comment1', 'comment2'], obo_lines)
        
        self.assertEqual(len(obo_lines), 2)
        self.assertEqual(obo_lines[0], 'comment: comment1')
        self.assertEqual(obo_lines[1], 'comment: comment2')
    
    def test_write_field_is_a_dict(self):
        """Test writing is_a field with dictionary value"""
        obo_lines = []
        
        is_a_list = [
            {"id": "SBO:0000064", "name": "mathematical expression"},
            {"id": "SBO:0000065", "name": "another parent"}
        ]
        
        self.converter._write_field('is_a', is_a_list, obo_lines)
        
        self.assertEqual(len(obo_lines), 2)
        self.assertEqual(obo_lines[0], 'is_a: SBO:0000064 ! mathematical expression')
        self.assertEqual(obo_lines[1], 'is_a: SBO:0000065 ! another parent')
    
    def test_write_to_file(self):
        """Test writing OBO lines to file"""
        obo_lines = [
            'format-version: 1.2',
            'ontology: test',
            '',
            '[Term]',
            'id: SBO:0000001',
            'name: test'
        ]
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.obo', delete=False) as f:
            temp_file = f.name
        
        try:
            self.converter._write_to_file(obo_lines, temp_file)
            
            with open(temp_file, 'r', encoding='utf-8') as f:
                content = f.read()
            
            expected_content = '\n'.join(obo_lines) + '\n'
            self.assertEqual(content, expected_content)
            
        finally:
            os.unlink(temp_file)
    
    def test_write_to_file_empty_lines(self):
        """Test writing to file with empty lines handling"""
        obo_lines = [
            'format-version: 1.2',
            'ontology: test',
            ''
        ]
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.obo', delete=False) as f:
            temp_file = f.name
        
        try:
            self.converter._write_to_file(obo_lines, temp_file)
            
            with open(temp_file, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Should end with single newline
            self.assertTrue(content.endswith('\n'))
            self.assertFalse(content.endswith('\n\n'))
            
        finally:
            os.unlink(temp_file)
    
    def test_convert_minimal_json(self):
        """Test converting minimal JSON data"""
        minimal_data = {
            "header": {},
            "terms": []
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as json_file:
            json.dump(minimal_data, json_file)
            json_file_path = json_file.name
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.obo', delete=False) as obo_file:
            obo_file_path = obo_file.name
        
        try:
            # Should not raise an error
            self.converter.convert_json_to_obo(json_file_path, obo_file_path)
            
            # Verify file was created
            self.assertTrue(os.path.exists(obo_file_path))
            
            with open(obo_file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Should contain empty header section
            self.assertIn('\n', content)  # At least has empty line after header
            
        finally:
            os.unlink(json_file_path)
            os.unlink(obo_file_path)


if __name__ == '__main__':
    unittest.main()