import unittest
import tempfile
import os
import json
import shutil
from unittest.mock import Mock, patch, MagicMock
import sys

# Add the project root to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from src.ols_fetch_from_github.user_file_processor import UserFileProcessor
from src.ols_fetch_from_github.config import Config


class TestUserFileProcessor(unittest.TestCase):
    """Test cases for UserFileProcessor class"""
    
    def setUp(self):
        """Set up test fixtures"""
        self.test_dir = tempfile.mkdtemp()
        
        # Create mock config
        self.mock_config = Mock()
        self.mock_config.github_url = 'https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OBO.obo'
        self.mock_config.github_repo_owner = 'EBI-BioModels'
        self.mock_config.github_repo_name = 'SBO'
        self.mock_config.github_file_path = 'SBO_OBO.obo'
        self.mock_config.timestamp_format = '%Y%m%d_%H%M%S'
        
        # Create processor with mock config
        self.processor = UserFileProcessor(self.mock_config)
        
        # Then override the customer directory to use test directory
        self.processor.customer_file_dir = os.path.join(self.test_dir, "customerfile")
        self.processor._ensure_customer_dir()
        
        # Sample valid JSON data based on actual SBO data structure
        self.valid_json_data = {
            "header": {
                "format-version": "1.2",
                "remark": "Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)",
                "ontology": "http://biomodels.net/SBO/",
                "property_value": "owl:versionInfo \"28:08:2021 03:13\" xsd:string",
                "name": "Generated: 03:11:2021 07:00"
            },
            "terms": [
                {
                    "id": "SBO:0000000",
                    "name": "systems biology representation",
                    "comment": "Representation of an entity used in a systems biology knowledge reconstruction, such as a model, pathway, network."
                },
                {
                    "id": "SBO:0000001",
                    "name": "rate law",
                    "comment": "mathematical description that relates quantities of reactants to the reaction velocity.",
                    "is_a": [
                        {
                            "id": "SBO:0000064",
                            "name": "mathematical expression"
                        }
                    ]
                }
            ],
            "typedefs": [
                {
                    "id": "part:of",
                    "name": "part of",
                    "is_transitive": "true"
                }
            ]
        }
        
        # Sample OBO content based on actual SBO structure
        self.valid_obo_content = """format-version: 1.2
remark: Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)
ontology: http://biomodels.net/SBO/
property_value: owl:versionInfo "28:08:2021 03:13" xsd:string
name: Generated: 03:11:2021 07:00

[Term]
id: SBO:0000000
name: systems biology representation
comment: Representation of an entity used in a systems biology knowledge reconstruction, such as a model, pathway, network.

[Term]
id: SBO:0000001
name: rate law
comment: mathematical description that relates quantities of reactants to the reaction velocity.
is_a: SBO:0000064 ! mathematical expression

[Typedef]
id: part:of
name: part of
is_transitive: true
"""
    
    def tearDown(self):
        """Clean up test fixtures"""
        shutil.rmtree(self.test_dir, ignore_errors=True)
    
    def test_init(self):
        """Test initialization"""
        self.assertIsNotNone(self.processor)
        self.assertEqual(self.processor.processed_files, [])
        self.assertTrue(os.path.exists(self.processor.customer_file_dir))
        
        # Check that components are initialized
        self.assertIsNotNone(self.processor.config)
        self.assertIsNotNone(self.processor.obo_parser)
        self.assertIsNotNone(self.processor.file_converter)
        self.assertIsNotNone(self.processor.file_validator)
    
    def test_process_user_file_nonexistent(self):
        """Test processing non-existent file"""
        result = self.processor.process_user_file("/path/to/nonexistent/file.json")
        
        success, json_file, message = result
        self.assertFalse(success)
        self.assertIsNone(json_file)
        self.assertIn("File does not exist", message)
    
    def test_process_user_file_unsupported_format(self):
        """Test processing file with unsupported format"""
        # Create a test file with unsupported extension
        test_file = os.path.join(self.test_dir, "test.txt")
        with open(test_file, 'w') as f:
            f.write("unsupported content")
        
        result = self.processor.process_user_file(test_file)
        
        success, json_file, message = result
        self.assertFalse(success)
        self.assertIsNone(json_file)
        self.assertIn("Unsupported file type", message)
    
    @patch('src.ols_fetch_from_github.user_file_processor.shutil.copy2')
    def test_process_user_file_copy_failure(self, mock_copy):
        """Test processing when file copy fails"""
        mock_copy.side_effect = Exception("Copy failed")
        
        # Create a test JSON file
        test_file = os.path.join(self.test_dir, "test.json")
        with open(test_file, 'w') as f:
            json.dump(self.valid_json_data, f)
        
        result = self.processor.process_user_file(test_file)
        
        success, json_file, message = result
        self.assertFalse(success)
        self.assertIsNone(json_file)
        self.assertIn("Failed to copy file", message)
    
    def test_process_json_file_valid(self):
        """Test processing valid JSON file"""
        # Create a test JSON file
        test_file = os.path.join(self.processor.customer_file_dir, "test.json")
        with open(test_file, 'w', encoding='utf-8') as f:
            json.dump(self.valid_json_data, f)
        
        result = self.processor._process_json_file(test_file)
        
        success, json_file, message = result
        self.assertTrue(success)
        self.assertEqual(json_file, test_file)
        self.assertIn("validation successful", message)
        
        # Check processing record
        self.assertEqual(len(self.processor.processed_files), 1)
        record = self.processor.processed_files[0]
        self.assertEqual(record['original_file'], test_file)
        self.assertEqual(record['final_file'], test_file)
        self.assertEqual(record['type'], 'json')
        self.assertEqual(record['status'], 'validated')
    
    def test_process_json_file_invalid_json(self):
        """Test processing invalid JSON file"""
        # Create a test file with invalid JSON
        test_file = os.path.join(self.processor.customer_file_dir, "invalid.json")
        with open(test_file, 'w') as f:
            f.write("invalid json content {")
        
        result = self.processor._process_json_file(test_file)
        
        success, json_file, message = result
        self.assertFalse(success)
        self.assertIsNone(json_file)
        self.assertIn("JSON format error", message)
    
    def test_process_json_file_invalid_structure(self):
        """Test processing JSON file with invalid structure"""
        # Create a test file with invalid structure (missing required fields)
        invalid_data = {"header": {}}  # Missing 'terms' field
        test_file = os.path.join(self.processor.customer_file_dir, "invalid_structure.json")
        with open(test_file, 'w', encoding='utf-8') as f:
            json.dump(invalid_data, f)
        
        result = self.processor._process_json_file(test_file)
        
        success, json_file, message = result
        self.assertFalse(success)
        self.assertIsNone(json_file)
        self.assertIn("JSON structure validation failed", message)
    
    def test_process_obo_file_valid(self):
        """Test processing valid OBO file"""
        # Mock the components
        self.processor.obo_parser.parse_obo_file = Mock(return_value=self.valid_json_data)
        self.processor.file_converter.convert_json_to_obo = Mock()
        self.processor.file_validator.validate_roundtrip_conversion = Mock(return_value=True)
        
        # Create a test OBO file
        test_file = os.path.join(self.processor.customer_file_dir, "test.obo")
        with open(test_file, 'w', encoding='utf-8') as f:
            f.write(self.valid_obo_content)
        
        result = self.processor._process_obo_file(test_file)
        
        success, json_file, message = result
        self.assertTrue(success)
        self.assertTrue(json_file.endswith("_user_upload.json"))
        self.assertIn("converted to JSON and validation successful", message)
        
        # Verify component method calls
        self.processor.obo_parser.parse_obo_file.assert_called_once_with(test_file)
        self.processor.file_converter.convert_json_to_obo.assert_called_once()
        self.processor.file_validator.validate_roundtrip_conversion.assert_called_once()
        
        # Check processing record
        self.assertEqual(len(self.processor.processed_files), 1)
        record = self.processor.processed_files[0]
        self.assertEqual(record['original_file'], test_file)
        self.assertEqual(record['type'], 'obo')
        self.assertEqual(record['status'], 'converted_and_validated')
        
        # Verify original OBO file was cleaned up
        self.assertFalse(os.path.exists(test_file))
    
    def test_process_obo_file_parse_error(self):
        """Test processing OBO file with parse error"""
        self.processor.obo_parser.parse_obo_file = Mock(side_effect=Exception("Parse error"))
        
        # Create a test OBO file
        test_file = os.path.join(self.processor.customer_file_dir, "test.obo")
        with open(test_file, 'w', encoding='utf-8') as f:
            f.write(self.valid_obo_content)
        
        result = self.processor._process_obo_file(test_file)
        
        success, json_file, message = result
        self.assertFalse(success)
        self.assertIsNone(json_file)
        self.assertIn("Error processing OBO file", message)
    
    def test_process_obo_file_invalid_structure(self):
        """Test processing OBO file that results in invalid JSON structure"""
        # Mock parser to return invalid JSON structure
        invalid_data = {"header": {}}  # Missing 'terms' field
        self.processor.obo_parser.parse_obo_file = Mock(return_value=invalid_data)
        
        # Create a test OBO file
        test_file = os.path.join(self.processor.customer_file_dir, "test.obo")
        with open(test_file, 'w', encoding='utf-8') as f:
            f.write(self.valid_obo_content)
        
        result = self.processor._process_obo_file(test_file)
        
        success, json_file, message = result
        self.assertFalse(success)
        self.assertIsNone(json_file)
        self.assertIn("Converted JSON structure validation failed", message)
    
    def test_process_obo_file_roundtrip_failure(self):
        """Test processing OBO file with roundtrip validation failure"""
        # Mock components
        self.processor.obo_parser.parse_obo_file = Mock(return_value=self.valid_json_data)
        self.processor.file_converter.convert_json_to_obo = Mock()
        self.processor.file_validator.validate_roundtrip_conversion = Mock(return_value=False)
        
        # Create a test OBO file
        test_file = os.path.join(self.processor.customer_file_dir, "test.obo")
        with open(test_file, 'w', encoding='utf-8') as f:
            f.write(self.valid_obo_content)
        
        result = self.processor._process_obo_file(test_file)
        
        success, json_file, message = result
        self.assertFalse(success)
        self.assertIsNone(json_file)
        self.assertIn("Roundtrip conversion validation failed", message)
    
    def test_cleanup_temp_files(self):
        """Test cleanup of temporary files"""
        # Create test files
        file1 = os.path.join(self.test_dir, "temp1.json")
        file2 = os.path.join(self.test_dir, "temp2.obo")
        file3 = os.path.join(self.test_dir, "nonexistent.txt")
        
        with open(file1, 'w') as f:
            f.write("test content 1")
        with open(file2, 'w') as f:
            f.write("test content 2")
        
        # Verify files exist
        self.assertTrue(os.path.exists(file1))
        self.assertTrue(os.path.exists(file2))
        self.assertFalse(os.path.exists(file3))
        
        # Clean up files
        self.processor._cleanup_temp_files([file1, file2, file3])
        
        # Verify files are removed
        self.assertFalse(os.path.exists(file1))
        self.assertFalse(os.path.exists(file2))
    
    def test_validate_json_structure_valid(self):
        """Test JSON structure validation with valid data"""
        result = self.processor._validate_json_structure(self.valid_json_data)
        
        self.assertTrue(result['valid'])
        self.assertEqual(result['message'], "JSON structure validation passed")
        
        stats = result['stats']
        self.assertEqual(stats['header_fields'], 5)  # All header fields in real data
        self.assertEqual(stats['total_terms'], 2)
        self.assertTrue(stats['has_typedefs'])
        self.assertEqual(stats['typedef_count'], 1)
    
    def test_validate_json_structure_missing_header(self):
        """Test JSON structure validation with missing header"""
        invalid_data = {"terms": []}
        result = self.processor._validate_json_structure(invalid_data)
        
        self.assertFalse(result['valid'])
        self.assertIn("Missing required field: header", result['message'])
    
    def test_validate_json_structure_missing_terms(self):
        """Test JSON structure validation with missing terms"""
        invalid_data = {"header": {}}
        result = self.processor._validate_json_structure(invalid_data)
        
        self.assertFalse(result['valid'])
        self.assertIn("Missing required field: terms", result['message'])
    
    def test_validate_json_structure_invalid_header_type(self):
        """Test JSON structure validation with invalid header type"""
        invalid_data = {"header": "should be object", "terms": []}
        result = self.processor._validate_json_structure(invalid_data)
        
        self.assertFalse(result['valid'])
        self.assertIn("Header field must be an object", result['message'])
    
    def test_validate_json_structure_invalid_terms_type(self):
        """Test JSON structure validation with invalid terms type"""
        invalid_data = {"header": {}, "terms": "should be array"}
        result = self.processor._validate_json_structure(invalid_data)
        
        self.assertFalse(result['valid'])
        self.assertIn("Terms field must be an array", result['message'])
    
    def test_validate_json_structure_invalid_term_type(self):
        """Test JSON structure validation with invalid term type"""
        invalid_data = {"header": {}, "terms": ["should be object"]}
        result = self.processor._validate_json_structure(invalid_data)
        
        self.assertFalse(result['valid'])
        self.assertIn("Term 1 is not an object", result['message'])
    
    def test_validate_json_structure_term_missing_id(self):
        """Test JSON structure validation with term missing id"""
        invalid_data = {
            "header": {},
            "terms": [{"name": "missing id term"}]
        }
        result = self.processor._validate_json_structure(invalid_data)
        
        self.assertFalse(result['valid'])
        self.assertIn("Term 1 missing id field", result['message'])
    
    def test_validate_json_structure_term_missing_name(self):
        """Test JSON structure validation with term missing name"""
        invalid_data = {
            "header": {},
            "terms": [{"id": "SBO:0000001"}]
        }
        result = self.processor._validate_json_structure(invalid_data)
        
        self.assertFalse(result['valid'])
        self.assertIn("Term 1 missing name field", result['message'])
    
    def test_validate_json_structure_exception(self):
        """Test JSON structure validation with exception"""
        result = self.processor._validate_json_structure(None)
        
        self.assertFalse(result['valid'])
        self.assertIn("Error during validation", result['message'])
    
    def test_copy_file_to_customer_dir(self):
        """Test copying file to customer directory"""
        # Create source file
        source_file = os.path.join(self.test_dir, "source.json")
        with open(source_file, 'w') as f:
            json.dump(self.valid_json_data, f)
        
        result = self.processor._copy_file_to_customer_dir(source_file)
        
        self.assertIsNotNone(result)
        self.assertTrue(result.endswith("source.json"))
        self.assertTrue(os.path.exists(result))
        
        # Verify content is identical
        with open(result, 'r') as f:
            copied_data = json.load(f)
        self.assertEqual(copied_data, self.valid_json_data)
    
    @patch('src.ols_fetch_from_github.user_file_processor.shutil.copy2')
    def test_copy_file_to_customer_dir_failure(self, mock_copy):
        """Test copying file to customer directory with failure"""
        mock_copy.side_effect = Exception("Copy failed")
        
        # Create source file
        source_file = os.path.join(self.test_dir, "source.json")
        with open(source_file, 'w') as f:
            json.dump(self.valid_json_data, f)
        
        result = self.processor._copy_file_to_customer_dir(source_file)
        
        self.assertIsNone(result)
    
    def test_get_processing_summary(self):
        """Test getting processing summary"""
        # Add some processing records
        self.processor.processed_files = [
            {
                'original_file': '/path/to/file1.json',
                'final_file': '/path/to/file1.json',
                'type': 'json',
                'status': 'validated'
            },
            {
                'original_file': '/path/to/file2.obo',
                'final_file': '/path/to/file2.json',
                'type': 'obo',
                'status': 'converted_and_validated'
            }
        ]
        
        summary = self.processor.get_processing_summary()
        
        self.assertEqual(summary['total_processed'], 2)
        self.assertEqual(len(summary['files']), 2)
        self.assertEqual(summary['files'][0]['type'], 'json')
        self.assertEqual(summary['files'][1]['type'], 'obo')
    
    def test_cleanup_old_files(self):
        """Test cleanup of old files"""
        # Create some old files in customer directory
        old_file1 = os.path.join(self.processor.customer_file_dir, "old1.json")
        old_file2 = os.path.join(self.processor.customer_file_dir, "old2.obo")
        
        with open(old_file1, 'w') as f:
            f.write("old content 1")
        with open(old_file2, 'w') as f:
            f.write("old content 2")
        
        # Verify files exist
        self.assertTrue(os.path.exists(old_file1))
        self.assertTrue(os.path.exists(old_file2))
        
        # Clean up
        self.processor._cleanup_old_files()
        
        # Verify files are removed
        self.assertFalse(os.path.exists(old_file1))
        self.assertFalse(os.path.exists(old_file2))
    
    def test_ensure_customer_dir(self):
        """Test ensuring customer directory exists"""
        # Remove the directory
        shutil.rmtree(self.processor.customer_file_dir)
        self.assertFalse(os.path.exists(self.processor.customer_file_dir))
        
        # Call ensure method
        self.processor._ensure_customer_dir()
        
        # Verify directory is created
        self.assertTrue(os.path.exists(self.processor.customer_file_dir))


if __name__ == '__main__':
    unittest.main()