import unittest
import json
import tempfile
import os
from unittest.mock import patch, mock_open
import sys

# Add the project root to the path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from src.ols_fetch_from_github.file_comparator import FileComparator


class TestFileComparator(unittest.TestCase):
    """Test cases for FileComparator class"""
    
    def setUp(self):
        """Set up test fixtures"""
        self.comparator = FileComparator()
        
        self.old_data = {
            "header": {
                "format-version": "1.2",
                "remark": "Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)",
                "ontology": "http://biomodels.net/SBO/",
                "property_value": "owl:versionInfo \"28:08:2021 03:13\" xsd:string",
                "name": "Generated: 03:11:2021 07:00"
            },
            "terms": [
                {
                    "id": "SBO:0000001",
                    "name": "rate law",
                    "comment": "mathematical description that relates quantities of reactants to the reaction velocity.",
                    "is_a": [
                        {
                            "id": "SBO:0000064",
                            "name": "mathematical expression"
                        }
                    ]
                },
                {
                    "id": "SBO:0000002", 
                    "name": "quantitative systems description parameter",
                    "comment": "A numerical value that defines certain characteristics of systems or system functions.",
                    "is_a": [
                        {
                            "id": "SBO:0000545",
                            "name": "systems description parameter"
                        }
                    ]
                }
            ],
            "typedefs": [
                {
                    "id": "part:of",
                    "name": "part of",
                    "is_transitive": "true"
                }
            ]
        }
        
        self.new_data = {
            "header": {
                "format-version": "1.2",
                "remark": "Systems Biology Ontology, OWL export generated by SBO Browser (http://www.ebi.ac.uk/sbo/)",
                "ontology": "http://biomodels.net/SBO/",
                "property_value": "owl:versionInfo \"28:08:2021 03:13\" xsd:string",
                "name": "Generated: 03:11:2021 07:00",
                "new-field": "added"
            },
            "terms": [
                {
                    "id": "SBO:0000001",
                    "name": "rate law",
                    "comment": "Updated mathematical description that relates quantities of reactants to the reaction velocity.",  # Changed
                    "is_a": [
                        {
                            "id": "SBO:0000064",
                            "name": "mathematical expression"
                        }
                    ]
                },
                {
                    "id": "SBO:0000003",  # New term
                    "name": "participant role",
                    "comment": "The function of a physical or conceptual entity, that is its role, in the execution of an event or process.",
                    "is_a": [
                        {
                            "id": "SBO:0000000",
                            "name": "systems biology representation"
                        }
                    ]
                }
                # SBO:0000002 removed
            ],
            "typedefs": [
                {
                    "id": "part:of",
                    "name": "part of",
                    "is_transitive": "true"
                },
                {
                    "id": "has:part",  # New typedef
                    "name": "has part",
                    "is_transitive": "true"
                }
            ]
        }
    
    def test_compare_json_files_success(self):
        """Test successful JSON file comparison"""
        # Create temporary files
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as old_file:
            json.dump(self.old_data, old_file)
            old_file_path = old_file.name
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as new_file:
            json.dump(self.new_data, new_file)
            new_file_path = new_file.name
        
        try:
            result = self.comparator.compare_json_files(old_file_path, new_file_path)
            
            # Verify overall structure
            self.assertIsNotNone(result)
            self.assertTrue(result['has_changes'])
            
            # Verify header changes
            header_changes = result['header_changes']
            self.assertEqual(header_changes['new-field']['action'], 'added')
            self.assertEqual(header_changes['new-field']['new_value'], 'added')
            
            # Verify term changes
            term_changes = result['term_changes']
            
            # Check added terms
            self.assertEqual(len(term_changes['added']), 1)
            added_term = term_changes['added'][0]
            self.assertEqual(added_term['id'], 'SBO:0000003')
            self.assertEqual(added_term['name'], 'participant role')
            
            # Check deleted terms
            self.assertEqual(len(term_changes['deleted']), 1)
            deleted_term = term_changes['deleted'][0]
            self.assertEqual(deleted_term['id'], 'SBO:0000002')
            
            # Check updated terms
            self.assertEqual(len(term_changes['updated']), 1)
            updated_term = term_changes['updated'][0]
            self.assertEqual(updated_term['id'], 'SBO:0000001')
            self.assertIn('comment', updated_term['field_changes'])
            self.assertEqual(updated_term['field_changes']['comment']['action'], 'updated')
            
            # Verify typedef changes
            typedef_changes = result['typedef_changes']
            self.assertEqual(len(typedef_changes['added']), 1)
            self.assertEqual(typedef_changes['added'][0]['id'], 'has:part')
            
            # Verify statistics
            stats = result['stats']
            self.assertEqual(stats['terms_added'], 1)
            self.assertEqual(stats['terms_deleted'], 1)
            self.assertEqual(stats['terms_updated'], 1)
            self.assertEqual(stats['typedefs_added'], 1)
            self.assertEqual(stats['typedefs_deleted'], 0)
            self.assertEqual(stats['typedefs_updated'], 0)
            self.assertTrue(stats['header_updated'])
            
        finally:
            os.unlink(old_file_path)
            os.unlink(new_file_path)
    
    def test_compare_json_files_no_changes(self):
        """Test comparison with no changes"""
        # Create identical files
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as old_file:
            json.dump(self.old_data, old_file)
            old_file_path = old_file.name
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as new_file:
            json.dump(self.old_data, new_file)  # Same data
            new_file_path = new_file.name
        
        try:
            result = self.comparator.compare_json_files(old_file_path, new_file_path)
            
            self.assertIsNotNone(result)
            self.assertFalse(result['has_changes'])
            self.assertEqual(len(result['header_changes']), 0)
            self.assertEqual(len(result['term_changes']['added']), 0)
            self.assertEqual(len(result['term_changes']['deleted']), 0)
            self.assertEqual(len(result['term_changes']['updated']), 0)
            
        finally:
            os.unlink(old_file_path)
            os.unlink(new_file_path)
    
    def test_compare_json_files_file_error(self):
        """Test comparison with file reading error"""
        result = self.comparator.compare_json_files("nonexistent1.json", "nonexistent2.json")
        
        self.assertIsNone(result)
    
    def test_compare_headers(self):
        """Test header comparison"""
        old_header = {"version": "1.0", "name": "test"}
        new_header = {"version": "2.0", "name": "test", "author": "new"}
        
        changes = self.comparator._compare_headers(old_header, new_header)
        
        self.assertEqual(changes['version']['action'], 'updated')
        self.assertEqual(changes['version']['old_value'], '1.0')
        self.assertEqual(changes['version']['new_value'], '2.0')
        self.assertEqual(changes['author']['action'], 'added')
        self.assertEqual(changes['author']['new_value'], 'new')
    
    def test_compare_terms(self):
        """Test terms comparison"""
        old_terms = [
            {"id": "T1", "name": "term1"},
            {"id": "T2", "name": "term2"}
        ]
        new_terms = [
            {"id": "T1", "name": "term1_updated"},  # Updated
            {"id": "T3", "name": "term3"}           # Added
            # T2 deleted
        ]
        
        changes = self.comparator._compare_terms(old_terms, new_terms)
        
        self.assertEqual(len(changes['added']), 1)
        self.assertEqual(changes['added'][0]['id'], 'T3')
        
        self.assertEqual(len(changes['deleted']), 1)
        self.assertEqual(changes['deleted'][0]['id'], 'T2')
        
        self.assertEqual(len(changes['updated']), 1)
        self.assertEqual(changes['updated'][0]['id'], 'T1')
    
    def test_compare_term_fields(self):
        """Test term field comparison"""
        old_term = {"id": "T1", "name": "old", "comment": "definition"}
        new_term = {"id": "T1", "name": "new", "is_a": "added"}
        
        changes = self.comparator._compare_term_fields(old_term, new_term)
        
        self.assertEqual(changes['name']['action'], 'updated')
        self.assertEqual(changes['name']['old_value'], 'old')
        self.assertEqual(changes['name']['new_value'], 'new')
        
        self.assertEqual(changes['comment']['action'], 'deleted')
        self.assertEqual(changes['comment']['old_value'], 'definition')
        
        self.assertEqual(changes['is_a']['action'], 'added')
        self.assertEqual(changes['is_a']['new_value'], 'added')


if __name__ == '__main__':
    unittest.main()